services:
  app:
    image: node:20
    working_dir: /app
    command: >
      bash -lc "npm install --production &&
                 node server.js"
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - ./backend:/app:ro
      - valpor_node_modules:/app/node_modules
    restart: always

  web:
    image: nginx:alpine
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  valpor_node_modules:
    driver: local
